name: CI - Vérification HTML

on:
  push:
    branches:
      - VERIF

jobs:
  html-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Installer djlint
        run: pip install djlint
        
      - name: Lancer le linter
        run: djlint index.html --lint
