name: Deploiement PRO

on:
  push:
    branches:
      - PRO

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Lancer le serveur et tester avec curl
        shell: powershell
        run: |
          echo "Démarrage du serveur web..."
          # On lance le serveur en tâche de fond dans PowerShell
          Start-Process -NoNewWindow -FilePath "python" -ArgumentList "-m http.server 8000"
          
          # On attend 3 petites secondes pour être sûr qu'il est bien démarré
          Start-Sleep -Seconds 3
          
          echo "Test de la connexion avec curl :"
          # On fait le curl directement ici !
          curl http://localhost:8000
