name: Deploiement PRO

on:
  push:
    branches:
      - PRO

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Lancer un serveur web local
        run: |
          echo "Le site est prêt sur le runner"
          # On utilise python pour lancer un petit serveur web sur le port 8000
          start /B python -m http.server 8000
